### ISSUE TITLE
BPE code used in source and target data

### ISSUE THREAD

**Issue by xixiddd** [nusnlp/mlconvgec2018#12]
Hi, Shamil Chollampatt.
In the _Model and Training Details_ Section of your paper, you said that "**Each of the source and target vocabularies consists of 30K most frequent BPE tokens from the source and target side of the parallel data, respectively.**", but according to this [line](https://github.com/nusnlp/mlconvgec2018/blob/7fedfe8b9061627cc38aa16fe8c3974d6d729920/training/preprocess.sh#L23) in the preprocessing scripts(i.e. training/preprocess.sh), it seems that you only use the target-end data to learn BPE codes and then, apply it to both source and target data.

**Comment by shamilcm** [comment]
The BPE model is trained using 30,000 operations using the target side of the training data according to the [line](https://github.com/nusnlp/mlconvgec2018/blob/7fedfe8b9061627cc38aa16fe8c3974d6d729920/training/preprocess.sh#L23) that you pointed to. The source/target vocabularies for the encoder-decoder model consist of 30,000 most frequent subwords (or BPE segmented tokens) from the source/target sides of the parallel data (see [line](https://github.com/nusnlp/mlconvgec2018/blob/7fedfe8b9061627cc38aa16fe8c3974d6d729920/training/preprocess.sh#L41)) .
