### ISSUE TITLE
How you do validation/stop training

### ISSUE THREAD

**Issue by xixiddd** [nusnlp/mlconvgec2018#13]
Hi,
In _Model and Training Details_ section of your paper, you said that "**We use early stopping and select the best model based on the F\_0.5 score on the development set.**". But to my knowledge, it seems that FairSeq can not do validation based on F\_0.5, so my question(clarification) is
- In FairSeq, the Early-Stop is only triggered when current learning rate < min-lr ?
- after the FairSeq training process finished, the model paramters will be seved as _checkpoint\_1.pt_ , _checkpoint\_2.pt_, ......, _checkpoint\_best.pt_,  _checkpoint\_last.pt_, then you use the _checkpoint_best.pt_ file directly, or manually select a checkpoint among all *.pt files as "best model" based on the F\_0.5 score on development set ?

Many thanks

**Comment by shamilcm** [comment]
Yes, after Fairseq training finishes (using the early stopping criteria based on learning rate), the checkpoint that has the highest F<sub>0.5</sub> on the development data is selected as the final model.
