### ISSUE TITLE
Python error: <stdin> is a directory, cannot continue

### ISSUE THREAD

**Issue by h123c** [nusnlp/mlconvgec2018#17]
hello:
      I get some error when I run the command of "./run.sh /home/.../mlconvgec2018/data/test/conll14st-test /home/.../mlconvgec2018/outputs 1 /home/...mlconvgec2018/models/mlconv".It shows Python error: <stdin> is a directory, cannot continue.Can you help me?

**Comment by shamilcm** [comment]
<input_file> should be the full path to the tokenized input file as mentioned in the README and not the test dataset directory.

**Comment by h123c** [comment]
@shamilcm OK,thank you.
