### ISSUE TITLE
How to use language model (94Bcclm.trie)?

### ISSUE THREAD

**Issue by spurscoder** [nusnlp/mlconvgec2018#19]
Hi,
When I running this command:
```
./run.sh data/test/conll14st-test/conll14st-test.tok.src \
             outputs_embed_eolm \
             5 \
             models/mlconv_embed \
             models/reranker_weights/mlconv_embed_4ens_eo_lm.weights.txt \
             eolm
```
I have encountered this problem
![image](https://user-images.githubusercontent.com/9803166/53190931-9875a180-3645-11e9-9748-99b095a14bb3.png)
It looks like that: "The format of language model is something wrong".
So, I google some suggests. They suggest that: change "\*.trie" files to "\*.arpa" files.
But, here is new problems:
![image](https://user-images.githubusercontent.com/9803166/53191627-42a1f900-3647-11e9-88a9-3a81a7be0991.png)
It seems that: I need the vocab of the language model. But there is no vocab files.

Finally, could you tell me, "How to use the language model file(94cclm.trie)"?
THANKS YOU.

**Comment by shamilcm** [comment]
The Language model in .trie format will work fine. You need not convert to .arpa.

Make sure you have downloaded the 94bcclm.trie completely. Check if your file is 159523360 Kb.

**Comment by spurscoder** [comment]
Yes, that's the way.
I didn't download the 94bcclm.trie completely, 
Thanks.
