### ISSUE TITLE
An error about Compile and install PyTorch(0.2.0)

### ISSUE THREAD

**Issue by jiusigua** [nusnlp/mlconvgec2018#21]
@shamilcm  Hi , When I run the setup.py following README [https://github.com/shamilcm/fairseq-py](https://github.com/shamilcm/fairseq-py)I got a error:
(py3.5) gpower@gpower:~/zhangtianjiu/NLP/mlconvgec2018-master/software/fairseq-py/pytorch$ git reset --hard a03e5cb40938b6b3f3e6dbddf9cff8afdff72d1b HEAD is now at a03e5cb40 Remind users to submodule update. 
My development environment is Linux+ Anaconda3 + Python 3.5 + CUDA 9.0
Can you help me ? Thank you very much.

**Comment by shamilcm** [comment]
What is the error?

**Comment by jiusigua** [comment]
I don't know why，when I run `git reset --hard a03e5cb40938b6b3f3e6dbddf9cff8afdff72d1b`  , It returns the following sentence：
`HEAD is now at a03e5cb40 Remind users to submodule update.`
I wondered  it is an error of git, but I'm not sure.

**Comment by shamilcm** [comment]
There seems to be no error. Just proceed with the steps of installation.

-Shamil

**Comment by jiusigua** [comment]
Thanks, I ignore the previous question，and continue to run the following code. When I run the code:`NO_DISTRIBUTED=1 python setup.py install`
，I got another mistake:
`6 errors detected in the compilation of "/tmp/tmpxft_0000f321_00000000-11_all_gather.compute_61.cpp1.ii".
Makefile:121: recipe for target '/home/gpower/pytorch/torch/lib/build/nccl/obj/all_gather.o' failed
make[3]: *** [/home/gpower/pytorch/torch/lib/build/nccl/obj/all_gather.o] Error 1
make[3]: *** Waiting for unfinished jobs....
src/common_kernel.h(42): error: class "__half" has no member "x"

src/common_kernel.h(42): error: class "__half" has no member "x"

src/common_kernel.h(55): error: class "__half" has no member "x"

src/common_kernel.h(55): error: class "__half" has no member "x"

src/copy_kernel.h(28): error: class "__half" has no member "x"

src/copy_kernel.h(28): error: class "__half" has no member "x"

6 errors detected in the compilation of "/tmp/tmpxft_0000f356_00000000-11_broadcast.compute_61.cpp1.ii".
Makefile:121: recipe for target '/home/gpower/pytorch/torch/lib/build/nccl/obj/broadcast.o' failed
make[3]: *** [/home/gpower/pytorch/torch/lib/build/nccl/obj/broadcast.o] Error 1
6 errors detected in the compilation of "/tmp/tmpxft_0000f36e_00000000-11_reduce.compute_61.cpp1.ii".
Makefile:121: recipe for target '/home/gpower/pytorch/torch/lib/build/nccl/obj/reduce.o' failed
make[3]: *** [/home/gpower/pytorch/torch/lib/build/nccl/obj/reduce.o] Error 1
6 errors detected in the compilation of "/tmp/tmpxft_0000f339_00000000-11_all_reduce.compute_61.cpp1.ii".
6 errors detected in the compilation of "/tmp/tmpxft_0000f380_00000000-11_reduce_scatter.compute_61.cpp1.ii".
Makefile:121: recipe for target '/home/gpower/pytorch/torch/lib/build/nccl/obj/reduce_scatter.o' failed
make[3]: *** [/home/gpower/pytorch/torch/lib/build/nccl/obj/reduce_scatter.o] Error 1
Makefile:121: recipe for target '/home/gpower/pytorch/torch/lib/build/nccl/obj/all_reduce.o' failed
make[3]: *** [/home/gpower/pytorch/torch/lib/build/nccl/obj/all_reduce.o] Error 1
CMakeFiles/nccl.dir/build.make:60: recipe for target 'lib/libnccl.so' failed
make[2]: *** [lib/libnccl.so] Error 2
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/nccl.dir/all' failed
make[1]: *** [CMakeFiles/nccl.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`
Can you help me with this problem?

**Comment by shamilcm** [comment]
Have you figured out the issue? 

You can use our branch which works with a later version of Fairseq: https://github.com/nusnlp/mlconvgec2018/tree/fairseq0.5 and can use Pytorch 0.4  instead of the older version.
