### ISSUE TITLE
pytorch version?

### ISSUE THREAD

**Issue by xiaoshengjun** [nusnlp/mlconvgec2018#26]
Hi, which version of pytorch is use? Thank you.

**Comment by shamilcm** [comment]
Our fairseq0.5 branch (https://github.com/nusnlp/mlconvgec2018/tree/fairseq0.5) has been tested with Fairseq 0.5 and Pytorch 0.4.1.

The master branch contains original scripts for the AAAI-18 paper which was using a fork of older Fairseq (https://github.com/shamilcm/fairseq-py) which was tested with PyTorch 0.2.0post3 compiled from source. 

It maybe easier to setup and use the fairseq0.5 branch.

**Comment by xiaoshengjun** [comment]
Ok，thank you very much， but I see the maste branch software/download.sh , the fairseq is 0.7.2 version?

**Comment by shamilcm** [comment]
The download script downloads our fork, see lines: https://github.com/nusnlp/mlconvgec2018/blob/master/software/download.sh#L1-L6
