### ISSUE TITLE
pre-trainined embeddings.

### ISSUE THREAD

**Issue by xiaoshengjun** [nusnlp/mlconvgec2018#27]
hi, when I run the scripts 'train_embed.sh', something is wrong, and I use the pytorch 0.4.1, fairseq 0.5.0. Could you help me? Thank you.

+ set -e
+ source ../paths.sh
++++ dirname ../paths.sh
+++ cd ..
+++ pwd
++ BASE_DIR=/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5
++ DATA_DIR=/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/data
++ MODEL_DIR=/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/models
++ SCRIPTS_DIR=/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/scripts
++ SOFTWARE_DIR=/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/software
+ FAIRSEQPY=/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/software/fairseq-py
+ EMBED_PATH=/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/models/embeddings/wiki_model.vec
+ '[' '!' -f /search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/models/embeddings/wiki_model.vec ']'
+ SEED=1000
+ DATA_BIN_DIR=processed/bin
+ OUT_DIR=models/mlconv_embed/model1000/
+ mkdir -p models/mlconv_embed/model1000/
+ PYTHONPATH=/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/software/fairseq-py:
+ CUDA_VISIBLE_DEVICES=7
+ python3.6 /search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/software/fairseq-py/train.py --save-dir models/mlconv_embed/model1000/ --encoder-embed-dim 500 --encoder-embed-path /search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/models/embeddings/wiki_model.vec --decoder-embed-dim 500 --decoder-embed-path /search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/models/embeddings/wiki_model.vec --decoder-out-embed-dim 500 --dropout 0.2 --clip-norm 0.1 --lr 0.25 --min-lr 1e-4 --encoder-layers '[(1024,3)] * 7' --decoder-layers '[(1024,3)] * 7' --momentum 0.99 --max-epoch 100 --batch-size 96 --no-progress-bar --seed 1000 --arch fconv processed/bin
Namespace(arch='fconv', clip_norm=0.1, criterion='cross_entropy', data='processed/bin', decoder_attention='True', decoder_embed_dim=500, decoder_embed_path='/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/models/embeddings/wiki_model.vec', decoder_layers='[(1024,3)] * 7', decoder_out_embed_dim=500, device_id=0, distributed_backend='nccl', distributed_init_method=None, distributed_port=-1, distributed_rank=0, distributed_world_size=1, dropout=0.2, encoder_embed_dim=500, encoder_embed_path='/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/models/embeddings/wiki_model.vec', encoder_layers='[(1024,3)] * 7', fp16=False, keep_interval_updates=-1, left_pad_source='True', left_pad_target='False', log_format=None, log_interval=1000, lr=[0.25], lr_scheduler='reduce_lr_on_plateau', lr_shrink=0.1, max_epoch=100, max_sentences=96, max_sentences_valid=96, max_source_positions=1024, max_target_positions=1024, max_tokens=6000, max_update=0, min_lr=0.0001, momentum=0.99, no_epoch_checkpoints=False, no_progress_bar=True, no_save=False, normalization_constant=0.5, optimizer='nag', raw_text=False, restore_file='checkpoint_last.pt', save_dir='models/mlconv_embed/model1000/', save_interval=1, save_interval_updates=0, seed=1000, sentence_avg=False, share_input_output_embed=False, skip_invalid_size_inputs_valid_test=False, source_lang=None, target_lang=None, task='translation', train_subset='train', update_freq=[1], valid_subset='valid', validate_interval=1, weight_decay=0.0)
| [src] dictionary: 29693 types
| [trg] dictionary: 29793 types
| processed/bin train 1298911 examples
| processed/bin valid 5448 examples
Traceback (most recent call last):
  File "/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/software/fairseq-py/train.py", line 353, in <module>
    main(args)
  File "/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/software/fairseq-py/train.py", line 38, in main
    model = task.build_model(args)
  File "/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/software/fairseq-py/fairseq/tasks/fairseq_task.py", line 43, in build_model
    return models.build_model(args, self)
  File "/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/software/fairseq-py/fairseq/models/__init__.py", line 25, in build_model
    return ARCH_MODEL_REGISTRY[args.arch].build_model(args, task)
  File "/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/software/fairseq-py/fairseq/models/fconv.py", line 67, in build_model
    encoder_embed_dict = utils.parse_embedding(args.encoder_embed_path)
  File "/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/software/fairseq-py/fairseq/utils.py", line 260, in parse_embedding
    embed_dict[pieces[0]] = torch.Tensor([float(weight) for weight in pieces[1:]])
  File "/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/software/fairseq-py/fairseq/utils.py", line 260, in <listcomp>
    embed_dict[pieces[0]] = torch.Tensor([float(weight) for weight in pieces[1:]])
ValueError: could not convert string to float: 'l2018)

**Comment by shamilcm** [comment]
can you check if the embeddings file was properly downloaded `/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/models/embeddings/wiki_model.vec` ?
