### ISSUE TITLE
ImportError: cannot import name 'libbleu'

### ISSUE THREAD

**Issue by Ibuki1129** [nusnlp/mlconvgec2018#28]
Hi there. When I ran ./run.sh I got an error below.
I've been working on this issue for 5days yet I still cannot figure it out. 
so pls help me!

Here is what I put
./run.sh data/test/conll14st-test/conll14st-test.tok.src outputs 0 models/mlconv/model1.pt

And here is what I got

14st-test.tok.src outputs 0 models/mlconv/model1.pt
++ source paths.sh
+++++ dirname paths.sh
++++ cd .
++++ pwd
+++ BASE_DIR=/mnt/data/okabe/mlconvgec2018
+++ DATA_DIR=/mnt/data/okabe/mlconvgec2018/data
+++ MODEL_DIR=/mnt/data/okabe/mlconvgec2018/models
+++ SCRIPTS_DIR=/mnt/data/okabe/mlconvgec2018/scripts
+++ SOFTWARE_DIR=/mnt/data/okabe/mlconvgec2018/software
++ '[' 4 -ge 4 ']'
++ input_file=data/test/conll14st-test/conll14st-test.tok.src
++ output_dir=outputs
++ device=0
++ model_path=models/mlconv/model1.pt
++ '[' 4 -eq 6 ']'
++ [[ -d models/mlconv/model1.pt ]]
++ [[ -f models/mlconv/model1.pt ]]
++ models=models/mlconv/model1.pt
++ FAIRSEQPY=/mnt/data/okabe/mlconvgec2018/software/fairseq-py
++ NBEST_RERANKER=/mnt/data/okabe/mlconvgec2018/software/nbest-reranker
++ beam=12
++ nbest=12
++ threads=12
++ mkdir -p outputs
++ /mnt/data/okabe/mlconvgec2018/scripts/apply_bpe.py -c /mnt/data/okabe/mlconvgec2018/models/bpe_model/train.bpe.model
++ CUDA_VISIBLE_DEVICES=0
++ python /mnt/data/okabe/mlconvgec2018/software/fairseq-py/generate.py --no-progress-bar --path models/mlconv/model1.pt --beam 12 --nbest 12 --interactive --workers 12 /mnt/data/okabe/mlconvgec2018/models/data_bin
ERROR: missing libbleu.so. run `python setup.py install`
Traceback (most recent call last):
  File "/mnt/data/okabe/mlconvgec2018/software/fairseq-py/generate.py", line 13, in <module>
    from fairseq import bleu, options, utils, tokenizer
  File "/mnt/data/okabe/mlconvgec2018/software/fairseq-py/fairseq/bleu.py", line 18, in <module>
    raise e
  File "/mnt/data/okabe/mlconvgec2018/software/fairseq-py/fairseq/bleu.py", line 14, in <module>
    from fairseq import libbleu
ImportError: cannot import name 'libbleu'

As this error says can't import libbleu, and I assume it is caused by something about fairseq.
But as the guideline said I followed steps and installed PyTorch from source so I have no idea what is wrong.

I'll put info just in case,
Environmental: miniconda on Linux
PyTorch version: 1.3.0
Python version: 3.6.2

Thank you.

**Comment by shamilcm** [comment]
The original code for the paper used this fork & commit for Fairseq https://github.com/shamilcm/fairseq-py/commit/ceb2f1200c9e5b8bf42a1033e7638d3e8586609a. As written in the README there, it uses PyTorch 0.2 compiled from source. The whole setup is very outdated. You could alternatively use PyTorch 0.4.1 installed normally with Fairseq 0.5, if you  use scripts from `fairseq0.5` branch of this repo (https://github.com/nusnlp/mlconvgec2018/tree/fairseq0.5)

**Comment by Ibuki1129** [comment]
Thanks a lot for your quick and kind reply. I just tried what you told me and the error didn't show up anymore! 
But now another error came up. 

When I ran below
./run.sh ./data/test/conll14st-test/conll14st-test.tok.src ./data/test/conll14st-test/output 0 ./training/models/mlconv/model1000 

I got this error
++ source paths.sh
+++++ dirname paths.sh
++++ cd .
++++ pwd
+++ BASE_DIR=/mnt/data/okabe/mlconvgec2018
+++ DATA_DIR=/mnt/data/okabe/mlconvgec2018/data
+++ MODEL_DIR=/mnt/data/okabe/mlconvgec2018/models
+++ SCRIPTS_DIR=/mnt/data/okabe/mlconvgec2018/scripts
+++ SOFTWARE_DIR=/mnt/data/okabe/mlconvgec2018/software
++ '[' 4 -ge 4 ']'
++ input_file=./data/test/conll14st-test/conll14st-test.tok.src
++ output_dir=./data/test/conll14st-test/output
++ device=0
++ model_path=./training/models/mlconv/model1000
++ '[' 4 -eq 6 ']'
++ [[ -d ./training/models/mlconv/model1000 ]]
++ [[ -f ./training/models/mlconv/model1000 ]]
++ [[ ! -e ./training/models/mlconv/model1000 ]]
++ echo 'Model path not found: ./training/models/mlconv/model1000'
Model path not found: ./training/models/mlconv/model1000
++ FAIRSEQPY=/mnt/data/okabe/mlconvgec2018/software/fairseq-py
++ NBEST_RERANKER=/mnt/data/okabe/mlconvgec2018/software/nbest-reranker
++ beam=12
++ nbest=12
++ threads=12
++ mkdir -p ./data/test/conll14st-test/output
++ /mnt/data/okabe/mlconvgec2018/scripts/apply_bpe.py -c /mnt/data/okabe/mlconvgec2018/models/bpe_model/train.bpe.model
++ CUDA_VISIBLE_DEVICES=0
++ python /mnt/data/okabe/mlconvgec2018/software/fairseq-py/interactive.py --no-progress-bar --path --beam 12 --nbest 12 --interactive --workers 12 /mnt/data/okabe/mlconvgec2018/models/data_bin
usage: interactive.py [-h] [--no-progress-bar] [--log-interval N]
                      [--log-format {json,none,simple,tqdm}] [--seed N]
                      [--task TASK] [--skip-invalid-size-inputs-valid-test]
                      [--max-tokens N] [--max-sentences N]
                      [--gen-subset SPLIT] [--num-shards N] [--shard-id ID]
                      [--path FILE] [--remove-bpe [REMOVE_BPE]] [--cpu]
                      [--quiet] [--beam N] [--nbest N] [--max-len-a N]
                      [--max-len-b N] [--min-len N] [--no-early-stop]
                      [--unnormalized] [--no-beamable-mm] [--lenpen LENPEN]
                      [--unkpen UNKPEN] [--replace-unk [REPLACE_UNK]]
                      [--score-reference] [--prefix-size PS] [--sampling]
                      [--sampling-topk PS] [--sampling-temperature N]
                      [--buffer-size N]
interactive.py: error: argument --path: expected one argument

I found a similar issue someone had(you replied to him as well) so I used interactive.py instead of using generate.py. Sadly, I still have an error.

Thanks for your cooperate!

**Comment by shamilcm** [comment]
If you want to do single model evaluation, give the path to the model file,
not the directory.

In your earlier run, the path was `models/mlconv/model1.pt` Check if the
file is in the correct path and pass this to run.sh

**Comment by Ibuki1129** [comment]
I recheck the path and I tried it again then other error showed up.

I found a totally same error here as this one#3. So as you said at #3 , I've updated fairseq/utils.py which has 152lines of codes cuz I installed fairseq-py by running python setup.py build develop. But I still got the same error. To be honest, I'm not sure if I changed it correctly. 
So please take a look

Thank you.

Here is what I ran.
./run.sh data/test/conll14st-test/conll14st-test.tok.src outputs_embed_eolm 0 models/mlconv_embed models/reranker_weights/mlconv_embed_4ens_eo_lm.weights.txt

++ source paths.sh
+++++ dirname paths.sh
++++ cd .
++++ pwd
+++ BASE_DIR=/mnt/data/okabe/mlconvgec2018
+++ DATA_DIR=/mnt/data/okabe/mlconvgec2018/data
+++ MODEL_DIR=/mnt/data/okabe/mlconvgec2018/models
+++ SCRIPTS_DIR=/mnt/data/okabe/mlconvgec2018/scripts
+++ SOFTWARE_DIR=/mnt/data/okabe/mlconvgec2018/software
++ '[' 5 -ge 4 ']'
++ input_file=data/test/conll14st-test/conll14st-test.tok.src
++ output_dir=outputs_embed_eolm
++ device=0
++ model_path=models/mlconv_embed
++ '[' 5 -eq 6 ']'
++ [[ -d models/mlconv_embed ]]
+++ ls models/mlconv_embed/model1.pt models/mlconv_embed/model2.pt models/mlconv_embed/model3.pt models/mlconv_embed/model4.pt
+++ tr '\n' ' '
+++ sed 's| \([^$]\)|:\1|g'
++ models='models/mlconv_embed/model1.pt:models/mlconv_embed/model2.pt:models/mlconv_embed/model3.pt:models/mlconv_embed/model4.pt '
++ echo models/mlconv_embed/model1.pt:models/mlconv_embed/model2.pt:models/mlconv_embed/model3.pt:models/mlconv_embed/model4.pt
models/mlconv_embed/model1.pt:models/mlconv_embed/model2.pt:models/mlconv_embed/model3.pt:models/mlconv_embed/model4.pt
++ FAIRSEQPY=/mnt/data/okabe/mlconvgec2018/software/fairseq-py
++ NBEST_RERANKER=/mnt/data/okabe/mlconvgec2018/software/nbest-reranker
++ beam=12
++ nbest=12
++ threads=12
++ mkdir -p outputs_embed_eolm
++ python2.7 /mnt/data/okabe/mlconvgec2018/scripts/apply_bpe.py -c /mnt/data/okabe/mlconvgec2018/models/bpe_model/train.bpe.model
++ CUDA_VISIBLE_DEVICES=0
++ python3.6 /mnt/data/okabe/mlconvgec2018/software/fairseq-py/interactive.py --no-progress-bar --path models/mlconv_embed/model1.pt:models/mlconv_embed/model2.pt:models/mlconv_embed/model3.pt:models/mlconv_embed/model4.pt --beam 12 --nbest 12 /mnt/data/okabe/mlconvgec2018/models/data_bin --source-lang src --target-lang trg
Traceback (most recent call last):
  File "/mnt/data/okabe/mlconvgec2018/software/fairseq-py/interactive.py", line 162, in <module>
    main(args)
  File "/mnt/data/okabe/mlconvgec2018/software/fairseq-py/interactive.py", line 77, in main
    models, model_args = utils.load_ensemble_for_inference(model_paths, task)
  File "/mnt/data/okabe/mlconvgec2018/software/fairseq-py/fairseq/utils.py", line 156, in load_ensemble_for_inference
    model = task.build_model(args)
  File "/mnt/data/okabe/mlconvgec2018/software/fairseq-py/fairseq/tasks/fairseq_task.py", line 43, in build_model
    return models.build_model(args, self)
  File "/mnt/data/okabe/mlconvgec2018/software/fairseq-py/fairseq/models/__init__.py", line 25, in build_model
    return ARCH_MODEL_REGISTRY[args.arch].build_model(args, task)
  File "/mnt/data/okabe/mlconvgec2018/software/fairseq-py/fairseq/models/fconv.py", line 67, in build_model
    encoder_embed_dict = utils.parse_embedding(args.encoder_embed_path)
  File "/mnt/data/okabe/mlconvgec2018/software/fairseq-py/fairseq/utils.py", line 256, in parse_embedding
    with open(embed_path) as f_embed:
FileNotFoundError: [Errno 2] No such file or directory: '/home.local/shamil/wiki/wiki.bpe.fasttext/model.vec'

**Comment by Ibuki1129** [comment]
Thank you very much!
