### ISSUE TITLE
Output directory error while running run.sh in google colab

### ISSUE THREAD

**Issue by eloiyerpes** [nusnlp/mlconvgec2018#30]
Hi there,
I'm running this command in google colab:
!chmod +x run.sh
!./run.sh '/content/gdrive/My Drive/Colab Notebooks/mlconvgec2018/data/tmp/conll14st-test-data/noalt/official-2014.0.conll.ann' '/content/gdrive/My Drive/Colab Notebooks/mlconvgec2018/abc' 1 '/content/gdrive/My Drive/Colab Notebooks/mlconvgec2018/models/mlconv/model1.pt'

And this is what i get:

++ source paths.sh
+++++ dirname paths.sh
++++ cd .
++++ pwd
+++ BASE_DIR='/content/gdrive/My Drive/Colab Notebooks/mlconvgec2018'
+++ DATA_DIR='/content/gdrive/My Drive/Colab Notebooks/mlconvgec2018/data'
+++ MODEL_DIR='/content/gdrive/My Drive/Colab Notebooks/mlconvgec2018/models'
+++ SCRIPTS_DIR='/content/gdrive/My Drive/Colab Notebooks/mlconvgec2018/scripts'
+++ SOFTWARE_DIR='/content/gdrive/My Drive/Colab Notebooks/mlconvgec2018/software'
++ '[' 4 -ge 4 ']'
++ input_file='/content/gdrive/My Drive/Colab Notebooks/mlconvgec2018/data/tmp/conll14st-test-data/noalt/official-2014.0.conll.ann'
++ output_dir='/content/gdrive/My Drive/Colab Notebooks/mlconvgec2018/abc'
++ device=1
++ model_path='/content/gdrive/My Drive/Colab Notebooks/mlconvgec2018/models/mlconv/model1.pt'
++ '[' 4 -eq 6 ']'
++ [[ -d /content/gdrive/My Drive/Colab Notebooks/mlconvgec2018/models/mlconv/model1.pt ]]
++ [[ -f /content/gdrive/My Drive/Colab Notebooks/mlconvgec2018/models/mlconv/model1.pt ]]
++ models='/content/gdrive/My Drive/Colab Notebooks/mlconvgec2018/models/mlconv/model1.pt'
++ FAIRSEQPY='/content/gdrive/My Drive/Colab Notebooks/mlconvgec2018/software/fairseq-py'
++ NBEST_RERANKER='/content/gdrive/My Drive/Colab Notebooks/mlconvgec2018/software/nbest-reranker'
++ beam=12
++ nbest=12
++ threads=12
++ mkdir -p /content/gdrive/My Drive/Colab Notebooks/mlconvgec2018/abc
mkdir: cannot create directory ‘/content/gdrive/My’: Operation not supported

I'm getting errors because mkdir does not detect the blank spaces. How i should do it?
Thank you

**Comment by shamilcm** [comment]
Put double quotes around the file name within the code and in your
arguments to the bash script.
