### ISSUE TITLE
spell check

### ISSUE THREAD

**Issue by cwlinghk** [nusnlp/mlconvgec2018#9]
The paper contains a spell checked result (table 1).
May I know if this repository contains the spell checking model? 
Thanks a lot.

**Comment by shamilcm** [comment]
The spell checker and models are from another repository (https://github.com/nusnlp/smtgec2017) 

You have to use the commands in these lines in this script, and also use a dictionary/word list to identify the unknown words:  https://github.com/nusnlp/smtgec2017/blob/master/run.sh#L47-L68 if you are to use the spell checker independently.

In the case of using spell checker at the output of the encoder-decoder GEC system (or an SMT-based GEC system), the word list contains all the source words in the training data. Any other word is treated as unknown word.
